### ISSUE TITLE
Possibility to change order for a user

### ISSUE THREAD

**Issue by jdeniau** [assafgelber/slash-coffee#1]
Hi,

It would be awesome if one could change its order.

I would be glad to help, but I do not know ruby, and I'm stuck with active record: how can I recover the order id to update only this order id ? 

Thanks.

**Comment by assafgelber** [comment]
This is another thing I considered when building the integration, but didn't think it would be a use case that's prevalent enough to support. I'd be glad to help you get started if you want to take a stab at adding this yourself!

In order to get the relevant order, you'd want to first make sure that there is an active run for that `team_id`/`channel_id` combination and search for the current user's order using the `orderer_id`. If found, the only thing left would be to update the item according the new data that was received.

Please feel free to comment here if you need more guidance. Good luck!
