### ISSUE TITLE
Post list in channel after each order

### ISSUE THREAD

**Issue by jdeniau** [assafgelber/slash-coffee#2]
Is there a way to maybe add a configuration parameter to post list in the current channel after each order ?

Thanks

**Comment by assafgelber** [comment]
Thanks for the proposal!

It's something I definitely considered when building this in the first place, but ultimately decided against it. Mainly because I didn't want to spam everyone, especially when the list usually only concerns one user, he who is actually going to get the coffee.
I think the option to just run `/coffee list` is good enough for this for the time being, but I appreciate the idea! Thank you! 😸
